remove version badged
[![Version](https://img.shields.io/badge/Version-0.0.3-orange.svg)](https://img.shields.io/badge/Version-0.0.3-orange.svg)

because error

pandoc: Could not fetch https://img.shields.io/badge/Version-0.0.3-orange.svg
HttpExceptionRequest Request {
  host                 = "img.shields.io"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/badge/Version-0.0.3-orange.svg"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed Error_EOF))
Error: pandoc document conversion failed with error 67
Execution halted